services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  strapi:
    image: strapi/strapi:latest
    depends_on:
      - mysql
    environment:
      NODE_ENV: development

      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123

      APP_KEYS: "a,b,c,d"
      API_TOKEN_SALT: "salt"
      ADMIN_JWT_SECRET: "secret"
      JWT_SECRET: "secret"
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
    restart: unless-stopped

volumes:
  dbdata:
